# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:               S=klogW
tagline:             "Molecular Stimulation"
url:                 https://choderalab.github.io/klogw/
baseurl:             "https://choderalab.github.io/klogw/"

# About/contact
author:
  name:              John D. Chodera
  url:               http//choderalab.org
  email:             john.chodera@choderalab.org

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/choderalab/klogw

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
