# Dependencies
markdown:         kramdown
highlighter:      rouge

# Theme
remote_theme: benbalter/retlab

# Permalinks
permalink:        pretty

# Setup
title:               "S=k.logW"
tagline:             "Molecular Stimulation"
url:                 https://choderalab.github.io/klogw/
baseurl:             /

# About/contact
author:
  name:              John D. Chodera
  url:               http//choderalab.org
  urlname:           "Chodera lab"
  email:             john.chodera@choderalab.org

paginate:         5

# Custom vars
version:          2.1.0
excerpt_separator: "<!--more-->"

github:
  repo:           https://github.com/choderalab/klogw

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-remote

